# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop, develop/* ]
  pull_request:
    branches: [ develop, develop/* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: doxygen run
      run: "sudo apt-get update -yqq && sudo apt-get install doxygen && cd docs && doxygen"
    
    - uses: Algo-ryth-mix/sphinx-action@master
      with:
        docs-folder: "docs/"