# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop, develop/* ]
  pull_request:
    branches: [ develop, develop/* ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: make ci executable
      run: chmod +x ci.sh
    
    - name: I hate apt
      run: sudo apt-get update -y && sudo apt-get install -y cppcheck
    
    - name: god why
      run: cppcheck --version

    - name: execute ci
      run: ./ci.sh
